context:
  version: 0.0.4
  r_version: 4.3
package:
  name: r-tomics
  version: ${{ version }}
source:
  url: https://github.com/twillis209/r-tomics/releases/download/v${{ version
    }}/tomics_${{ version }}.tar.gz
  sha256: 13f18c72fb8cd0870f283e191b262cabbb4a590d52cafad4fd7b658fe424769d
build:
  noarch: generic
  script:
    - if: unix
      then:
        - mkdir -p inst
        - cp -R tests inst/tests
        - R CMD INSTALL --build .
requirements:
  host:
  - r-base >= ${{ r_version }}
  - r-data.table (>= 1.15)
  - r-dplyr
  - r-ggplot2
  - r-ggtext
  - r-ggbreak
  - r-magrittr
  - r-scales
  run:
  - r-base
  - r-data.table (>= 1.15)
  - r-dplyr
  - r-ggplot2
  - r-ggtext
  - r-ggbreak
  - r-magrittr
  - r-scales
tests:
- script:
  - Rscript -e "library('tomics');"
  - Rscript -e "library(tomics); testthat::test_package('tomics')"
  requirements:
    run:
    - r-testthat
about:
  homepage: https://github.com/twillis209/r-tomics
  summary: Useful functions for working with GWAS data.
  description: This package contains utility functions for working with GWAS data, e.g. drawing Manhattan plots and running a fixed-effect meta-analysis.
  license: MIT
  repository: https://github.com/twillis209/r-tomics
