context:
  version: 0.8.0
  r_version: 4.3
package:
  name: r-tomics
  version: ${{ version }}
source:
  url: https://github.com/twillis209/r-tomics/releases/download/v${{ version
    }}/tomics_${{ version }}.tar.gz
  sha256: 0ef05ec0a54e7b28a96dad03c809b9f5ebdf6b7ddf0a20f933c1e994f99c9ad8
build:
  script:
    - if: unix
      then:
        - mkdir -p inst
        - cp -R tests inst/tests
        - R CMD INSTALL --build .
requirements:
  host:
  - r-base >= ${{ r_version }}
  - r-data.table (>= 1.15)
  - r-dplyr
  - r-ggplot2
  - r-ggtext
  - r-ggbreak
  - r-magrittr
  - r-scales
  - r-ggrepel
  - r-tibble
  run:
  - r-base
  - r-data.table (>= 1.15)
  - r-dplyr
  - r-ggplot2
  - r-ggtext
  - r-ggbreak
  - r-magrittr
  - r-scales
  - r-ggrepel
  - r-tibble
tests:
- script:
  - Rscript -e "library('tomics');"
  - Rscript -e "library(tomics); testthat::test_package('tomics')"
  requirements:
    run:
    - r-testthat
    - r-vdiffr
about:
  homepage: https://github.com/twillis209/r-tomics
  summary: Useful functions for working with GWAS data.
  description: This package contains utility functions for working with GWAS data, e.g. drawing Manhattan plots and running a fixed-effect meta-analysis.
  license: MIT
  repository: https://github.com/twillis209/r-tomics
