context:
  version: 0.13.0
package:
  name: r-tomics
  version: ${{ version }}
source:
  url: https://github.com/twillis209/r-tomics/releases/download/v${{ version
    }}/tomics_${{ version }}.tar.gz
  sha256: b830ab4632d82f5e7adea7288597902670436e80c4cfa6a675f2f72a26b90d98
build:
  script:
    - if: unix
      then:
        - mkdir -p inst
        - cp -R tests inst/tests
        - R CMD INSTALL --build .
requirements:
  host:
  - r-base
  - r-data.table (>= 1.15)
  - r-dplyr
  - r-ggbreak
  - r-ggplot2
  - r-ggrepel
  - r-ggtext
  - r-magrittr
  - r-plotly
  - r-htmlwidgets
  - r-rlang
  - r-scales
  - r-tibble
  - r-tidyr
  - r-tidyselect
  run:
  - r-base
  - r-data.table (>= 1.15)
  - r-dplyr
  - r-ggbreak
  - r-ggplot2
  - r-ggrepel
  - r-ggtext
  - r-magrittr
  - r-plotly
  - r-htmlwidgets
  - r-rlang
  - r-scales
  - r-tibble
  - r-tidyr
  - r-tidyselect
tests:
- script:
  - Rscript -e "library('tomics');"
  - Rscript -e "library(tomics); testthat::test_package('tomics')"
  requirements:
    run:
    - r-testthat (>= 3.0.0)
    - r-vdiffr
about:
  homepage: https://github.com/twillis209/r-tomics
  summary: Useful functions for working with GWAS data.
  description: This package contains utility functions for working with GWAS data, e.g. drawing Manhattan plots and running a fixed-effect meta-analysis.
  license: MIT
  repository: https://github.com/twillis209/r-tomics
